# Generated by Django 5.0.7 on 2024-08-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_order_amount_alter_order_amount_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_due',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
    ]
